# Generated by Django 4.2 on 2025-12-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_draws', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('normal_wins', models.IntegerField(default=0)),
                ('hard_wins', models.IntegerField(default=0)),
                ('veteran_wins', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-total_wins', 'total_losses'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard'), ('veteran', 'Veteran')], default='normal', max_length=10)),
                ('mode', models.CharField(default='classic', max_length=20)),
                ('player_wins', models.IntegerField(default=0)),
                ('ai_wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_choice', models.CharField(max_length=20)),
                ('ai_choice', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gamesession')),
            ],
        ),
    ]
