# Generated by Django 4.2 on 2025-12-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('player_name', models.CharField(max_length=50)),
                ('mode', models.CharField(default='classic', max_length=20)),
                ('status', models.CharField(default='searching', max_length=20)),
                ('matched_game_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(default='classic', max_length=20)),
                ('player1_id', models.CharField(max_length=100)),
                ('player1_name', models.CharField(max_length=50)),
                ('player1_choice', models.CharField(blank=True, max_length=20, null=True)),
                ('player1_score', models.IntegerField(default=0)),
                ('player1_ready', models.BooleanField(default=False)),
                ('player2_id', models.CharField(max_length=100)),
                ('player2_name', models.CharField(max_length=50)),
                ('player2_choice', models.CharField(blank=True, max_length=20, null=True)),
                ('player2_score', models.IntegerField(default=0)),
                ('player2_ready', models.BooleanField(default=False)),
                ('current_round', models.IntegerField(default=1)),
                ('max_rounds', models.IntegerField(default=5)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('round_result', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
