# Generated by Django 4.2 on 2025-12-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_matchmakingqueue_onlinegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegame',
            name='forfeit_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='round_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
