# Generated by Django 4.2 on 2025-12-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_onlinegame_forfeit_by_onlinegame_round_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegame',
            name='player1_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='player2_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
